server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: local-book-event-update-notification
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: ${DB_PASSWORD:postgres}
    hikari:
      schema: public
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

notification:
  kafka:
    topic: book.event-notification.update
    groupId: ${spring.kafka.consumer.group-id}
    autoOffsetResetPolicy: earliest

